### PR TITLE
Refactoring Game

### PR DESCRIPTION
**Pull request by aislinnjeske**
Hey MaryLou and Fari! I'm taking a look at the game implementation and I'm walking through files one by one to try and makes things a tad more clear with comments and code. I've added java doc because the comments help, but it's a little hard to read the code with so many comments. I don't think we need to keep track of what pieces have been captured. I think we can just delete them from the board so that when we reload the game, we don't have to worry about creating that piece again, but not putting it on the board. I'm also wondering if we need a player class? Let me know your thoughts. I mostly made changes to GameBoard, so let me know your thoughts/any revisions I made that I shouldn't have. 

Side Note: I deleted capturePiece() but put it back, so I know there are some inconsistencies. I am in the process of putting it back, just wanted to get some feedback early. A lot of your implementation is good and doesn't need to be changed, just need to move a few things around for clarity : )

### CODE REVIEW

**Comment by farikdk** [comment]
> Hey MaryLou and Fari! I'm taking a look at the game implementation and I'm walking through files one by one to try and makes things a tad more clear with comments and code. I've added java doc because the comments help, but it's a little hard to read the code with so many comments. I don't think we need to keep track of what pieces have been captured. I think we can just delete them from the board so that when we reload the game, we don't have to worry about creating that piece again, but not putting it on the board. I'm also wondering if we need a player class? Let me know your thoughts. I mostly made changes to GameBoard, so let me know your thoughts/any revisions I made that I shouldn't have.
> 
> Side Note: I deleted capturePiece() but put it back, so I know there are some inconsistencies. I am in the process of putting it back, just wanted to get some feedback early. A lot of your implementation is good and doesn't need to be changed, just need to move a few things around for clarity : )

**Comment by mlnash2** [comment]
Aislinn - 
     I agree with you that we may not need the Player class.  That was just there in case we ever wanted to do something like add any AI capability - something like have the player compete against the computer.  The player class just allowed us to quickly see what pieces that player has on the board.  They only other way to do it, is to scan through the board and look at the .player field in GamePiece.  
     The .capture field is in the GamePiece because it was an easy way to determine that the piece was gone.  We would not need that if we're not going to access pieces from Player.  
     However, we should be careful about removing capturePiece().  That is used to set the board square to null and take the piece off the board.  You could remove this line - pieceToBeCaptured.setCaptured(); from capturePiece() though if you're going to get rid of Player.
     Let me take a look at GameBoard.  There was a couple things that I did with placePiece and movePiece that I realized later were confusing.  I was going to clean that up.

**Comment by mlnash2** [comment]
Aislinn - Eventually I wanted to get to just one implementation of ValidateMove and performMove.  Although monkey is the only piece that can do a sequence of jumps and moves, I was pushing things toward using the array-based implementation for all pieces.  I'm afraid we haven't converted all our tests over just yet so I'm leaving both versions in place, but writing all new tests using the array-based method.

**Comment by farikdk** [comment]
@Aislinnjeske 
Refactoring looks good and smart to me! 
- I am not sure that removing .iscaptured() is necessary, as I guess we used it to check if a piece is still alive or already captured - 
Marylou: Is there any other specific reason that we need to be aware the presence or absence of a piece , are we going to use that for specific reason later ?

**Comment by aislinnjeske** [comment]
I agree with you both and as I said, I'm leaving capturePiece() in there.  @mlnash2 is there anything wrong with the way I changed GameBoard? Can't we just use that for the inconsistencies with placePiece and movePiece? The more refactoring you make, the more conflicts my branch will have

**Comment by mlnash2** [comment]
I don't want to create conflicts for you.  Last night, I was looking at the confusing methods - movePiece (2 versions) and placePiece to see if there was anything I could clean up.  I can leave that alone if you're fine with what's there for now.  
At this point, I can just add more tests to Fari's pieces and maybe refactor Crocodile methods if I think there's something useful I can "fix" there.  We thought it might be useful to add a test or two to each other's pieces to see if we can find any bugs.
Is there something I should start looking into.  One of the other features we want to add?  I'll probably need to pick Abby's brain to see how she's been testing and running things.  Or can you help with that too?

**Comment by aislinnjeske** [comment]
What did you say you wanted to work on? The front end right? I thought we gave tasks to everyone on Wednesday but maybe not. Maybe talk to abby and you can get a head start on the invitations? or help zach with communication

**Pull request closed without merging**
