### PR TITLE
Rictor form error handling

### PR DESCRIPTION
**Pull request by amrictor**
okay for real this time

### CODE REVIEW

**Comment by amrictor** [comment]
> Some of the assertion checks were removed in the game pieces tests. I'm not sure why they needed to be removed. Some of them have other checks that did remain in place, so might be OK but doesn't seem like it hurt anything to leave them in place.
> This one was especially concerrning since it now seems like there is no assertion left in the test - testMonkeyCantJumpSamePlayersPiece

Marylou, I changed the way that function works. It is now a void returning function that throws exceptions on failures. If an exception is thrown, a test will automatically fail.

**Comment by mlnash2** [comment]
Then shouldn't we have a check for an exception being thrown?  Especially in the case of the one monkey test that now seems to have no check.  Are there any checks for exceptions being thrown now instead?

**Comment by amrictor** [comment]
Yes, I'm also concerned at the amount of checks that happen in each test case; each unit test should generally test one specific thing. I added separate tests for expecting exceptions to be thrown.

**Comment by mlnash2** [comment]
Agree - there are too many checks in some tests.  I'm just concerned that we now have no coverage on specific moves.  If someone was checking for a boolean return and not looking at anything else (e.g. contents of a square at the end of the move) then without checking for exceptions in each case we now have no coverage.  
Is there a reason we needed to change from returning a boolean to throwing an exception?

**Comment by amrictor** [comment]
To keep our error handling clean and consistent...I believe we discussed this during last meeting and I think I outlined the changes I was making. We are throwing an exception with a descriptive message and catching it in the update factory so that we can send out an error to the client. I think it's cleaner and more understandable and descriptive. I don't understand where you think we're losing coverage. I'm fairly confident my changes keep functionality (of tests and product) identical to what we had previously.

**Comment by mlnash2** [comment]
Yes - I understood that we were changing our error handling between client and server.  That's fine if you want to make a unique exception for each failure type and catch it in UpdateFactory.  But I still am not 100% certain our test coverage is as good as it was before.  If Fari or I used ValidateMove() in the test, then it is probably OK.  But if we used performMove() in the test, then I'm not convinced it is the same coverage.  Here's is one case I found that has NO coverage now.  I'd have to look closely through all of our tests to see which ones were impacted.  There is absolutely NO check/assertion in this test anymore.

@Test(expected = Exception.class)
    public void testMonkeyCantJumpSamePlayersPiece() throws Exception {
        /* Start with initial board */
        MonkeyPiece monkey = (MonkeyPiece) congoGame.getGamePiece(6, 1);
        ArrayList<Integer> movesRow = new ArrayList<Integer>();
        ArrayList<Integer> movesCol = new ArrayList<Integer>();
        movesRow.add(4);
        movesCol.add(3);

        monkey.performMove(movesRow, movesCol, congoGame);
    }

**Comment by mlnash2** [comment]
I can merge this code so we can continue to make practice, but I think someone should look and see if there are now tests where coverage has been reduced.

**Comment by amrictor** [comment]
Test coverage is not determined by assertions. Exceptions also will cause tests to fail.

**Comment by mlnash2** [comment]
OK Abby.  I'll go ahead and merge.  I see 2-3 places that I may conflict with your changes.  I might want to consult with you if I get a lot of conflicts merging my stuff.

**Pull request merged**
