### PR TITLE
Added performMove().  Split up JUnit tests.  Added Game & Player class.

### PR DESCRIPTION
**Pull request by mlnash2**

### CODE REVIEW

**Comment by mlnash2** [comment]
Abby - Just note - I started splitting up the JUnit tests.  We'll have more split when Fari does the same with her tests.

**Comment by mlnash2** [comment]
@aislinnjeske - This code drop has the Player & Game classes.

**Comment by farikdk** [comment]
I have few questions write here not to forget to ask you !!!

1. in line 22, why did you call ValidateMove() in gamePiece  that return false ? 

2. why did you make class gamePiece abstract??

**Comment by mlnash2** [comment]
> 1. in line 22, why did you call ValidateMove() in gamePiece  that return false ?  What is its functionality?
     I did this so I could use ValidateMove() in performMove() and compile.  We should never call ValidateMove() on a GamePiece object - only on a specific piece.  Therefore I return false.  I add some appropriate comments.
> 2. why did you make class gamePiece abstract??
That was a mistake.  I removed it.

**Pull request merged**
